# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      target-branch: 'main' # Avoid updates to "staging".
      directory: '/telemetry/vscode'
      schedule:
          interval: 'daily'
      groups:
          jest:
              dependency-type: 'development'
              patterns:
                  - '*jest'
          types:
              dependency-type: 'development'
              patterns:
                  - '@types/*'

    - package-ecosystem: 'gradle'
      target-branch: 'main' # Avoid updates to "staging".
      directory: '/telemetry/jetbrains'
      schedule:
          interval: 'daily'

    - package-ecosystem: 'nuget'
      target-branch: 'main' # Avoid updates to "staging".
      directory: '/telemetry/csharp'
      schedule:
          interval: 'daily'
      groups:
          xunit:
              dependency-type: 'development'
              patterns:
                  - 'xunit'
                  - 'xunit.runner.visualstudio'
                  - 'xunit*'
                  - 'xunit.*'
              update-types:
                  - 'minor'
