# Documentation for configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      target-branch: 'main' # Avoid updates to "staging".
      commit-message:
          prefix: 'deps'
      directory: '/telemetry/vscode'
      schedule:
          interval: 'daily'
      groups:
          jest:
              patterns:
                  - '*jest'
          types:
              patterns:
                  - '@types/*'
          # other: # Catch-all to ensure dependabot updates other dependencies...
          #     patterns:
          #         - '*'

    - package-ecosystem: 'gradle'
      target-branch: 'main' # Avoid updates to "staging".
      commit-message:
          prefix: 'deps'
      directory: '/telemetry/jetbrains'
      schedule:
          interval: 'daily'

    - package-ecosystem: 'nuget'
      target-branch: 'main' # Avoid updates to "staging".
      commit-message:
          prefix: 'deps'
      directory: '/telemetry/csharp'
      schedule:
          interval: 'daily'
      groups:
          xunit:
              patterns:
                  - 'xunit'
                  - 'xunit.runner.visualstudio'
                  - 'xunit*'
                  - 'xunit.*'
              update-types:
                  - 'minor'
          # other: # Catch-all to ensure dependabot updates other dependencies...
          #     patterns:
          #         - '*'
