version: 0.2

env:
    variables:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            # Explicitly restore the .NET Framework projects or CodeBuild produces errors running dotnet build on the .sln :(
            - dotnet -d restore .\telemetry\csharp\AwsToolkit.Telemetry.Events\AwsToolkit.Telemetry.Events.csproj
            - dotnet -d restore .\telemetry\csharp\AwsToolkit.Telemetry.Events.Tests\AwsToolkit.Telemetry.Events.Tests.csproj

            # Restore everything (else)
            - dotnet -d restore ./telemetry/csharp/AwsToolkit.Telemetry.sln

            # Build
            - dotnet build -c Release ./telemetry/csharp/AwsToolkit.Telemetry.sln

            # Test
            - dotnet test -c Release ./telemetry/csharp/AwsToolkit.Telemetry.sln --logger trx --results-directory ./.testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './.testresults'
