version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto8

    build:
        commands:
            - |
                # TODO - iterate through the subdirectories to have one build script per runtime
                cd telemetry/jetbrains
                ./gradlew test

artifacts:
    files:
        - '**/*'

