version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18

    build:
        # Build and package the language server, then run tests.
        # Packaging takes place before the tests, in case tests mutate the output folder.
        # Packaged binaries will be emitted as CodeBuild artifacts.
        commands:
            - |
                cd lsp
                npm install
                npm run compile
                npm run package
                npm run test
artifacts:
    discard-paths: yes
    files:
        - lsp/app/**/bin/**
