version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16

    build:
        # Build and package the language server, then run tests.
        # Packaged binaries will be emitted as CodeBuild artifacts.
        commands:
            - |
                cd lsp
                npm install
                npm run compile
                npm run test

# TODO : IDE-10874 : establish a top level packaging command
#                npm run package-x64
# artifacts:
#     discard-paths: yes
#     files:
#         - lsp/bin/**
