name: CI for C# Toolkit Common Telemetry
on:
    push:
        branches: [master]
    pull_request:
        branches: [master, feature/*]

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: 1

jobs:
    build:
        name: Build and Test
        runs-on: windows-latest
        steps:
            - name: Sync Code
              uses: actions/checkout@v2
            - name: Build
              run: |
                  dotnet build -c Release .\telemetry\csharp\AwsToolkit.Telemetry.sln
            - name: Test
              run: |
                  dotnet test -c Release ./telemetry/csharp/AwsToolkit.Telemetry.sln
